### PR TITLE
Use DN instead of counts everywhere

### PR DESCRIPTION
**Pull request by wtbarnes**
In line with sunpy/sunpy#7585, this replaces the usage of `ct/count` with `DN` everywhere. This may cause some friction in terms of compatibility with sunpy as prior to v6, the units of any AIA map are converted to `ct` rather than `DN`. I'm not sure the best way to resolve that. We could of course just pin to >= v6, but that seems aggressive.

### CODE REVIEW

**Comment by nabobalis** [comment]
Consider this a breaking change? We can do a 0.9 release for it.

**Comment by wtbarnes** [comment]
> Consider this a breaking change? We can do a 0.9 release for it.

Yes, I would say so

**Comment by nabobalis** [comment]
I think a breaking changelog and its good to go.

**Comment by wtbarnes** [comment]
The docs build is failing,

```
/home/runner/work/aiapy/aiapy/.tox/build_docs/lib/python3.12/site-packages/aiapy/calibrate/prep.py:docstring of aiapy.calibrate.prep.degradation:1: WARNING: py:class reference target not found: Unit
/home/runner/work/aiapy/aiapy/.tox/build_docs/lib/python3.12/site-packages/aiapy/calibrate/uncertainty.py:docstring of aiapy.calibrate.uncertainty.estimate_error:1: WARNING: py:class reference target not found: Unit
/home/runner/work/aiapy/aiapy/.tox/build_docs/lib/python3.12/site-packages/aiapy/calibrate/uncertainty.py:docstring of aiapy.calibrate.uncertainty.estimate_error:1: WARNING: py:class reference target not found: Unit
/home/runner/work/aiapy/aiapy/.tox/build_docs/lib/python3.12/site-packages/aiapy/psf/psf.py:docstring of aiapy.psf.psf.psf:1: WARNING: py:class reference target not found: Unit
/home/runner/work/aiapy/aiapy/.tox/build_docs/lib/python3.12/site-packages/aiapy/response/channel.py:docstring of aiapy.response.channel.Channel:1: WARNING: py:class reference target not found: Unit
/home/runner/work/aiapy/aiapy/.tox/build_docs/lib/python3.12/site-packages/aiapy/util/util.py:docstring of aiapy.util.util.telescope_number:1: WARNING: py:class reference target not found: Unit
```

and I've not worked out why yet.

**Comment by nabobalis** [comment]
Just add it to the nickpicky list.

**Comment by wtbarnes** [comment]
Why do I always forget this…

**Review by nabobalis — APPROVED** [review]

**Comment by nabobalis** [comment]
We will pin the new version to sunpy 6.0 :P

**Pull request merged**
